apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-0
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-0
  template:
    metadata:
      labels:
        app: eureka-0
    spec:
      nodeName: k8s-node-0
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
        - name: eureka
          image: 192.168.0.109/ms-eureka
          command: ["java"]
          args: ["-jar", "/usr/local/eureka.jar","--spring.profiles.active=test","--server.port=8763","--spring.application.name=eureka-rs2","--eureka.instance.appname=eureka","--eureka.instance.hostname=k8s-node-0","--eureka-rs1.hostname=k8s-node-1","--eureka-rs1.port=8001","--eureka-rs2.hostname=k8s-node-2","--eureka-rs2.port=8002"]
          ports:
            - name: http
              containerPort: 8000
              hostPort: 8000
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---

apiVersion: v1
kind: Service
metadata:
  name: eureka-0
  namespace: ms
  labels:
    app: eureka-0
spec:
  ports:
    - port: 8000
      name: eureka-0
      targetPort: 8000
  selector:
    app: eureka-0