server:
  # 服务启动端口
  port: 8763
eureka:
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
      # 不对自己注册
    register-with-eureka: true
  server:
    # 关闭自我保护,如果不在线的服务会被服务中心直接剔除不保留 开发模式使用,生产环境禁止
    enable-self-preservation: false
  instance:
    # 注册中心打开后的链接
#    hostname: peer3
    prefer-ip-address: true

spring:
  application:
    #服务名字
    name: eureka

